### ISSUE TITLE
Make algorithm work with float input?

### ISSUE THREAD

**Issue by waldeland** [encukou/bresenham#3]
Hi! Great work!

Maybe it is possible to make algorithm work with float input by changing line 32 from:
_for x in range(dx + 1):_
to
_for x in range(int(dx + 1)):_
in bresenham.py.

**Comment by encukou** [comment]
Well, Bresenham's algorithm is famous for only dealing with ints, so you should only call it with ints :)

It would be possible to generalize to floats or fractional pixels, but that should have more sophisticated behavior – like [Wu's algorithm](https://en.wikipedia.org/wiki/Xiaolin_Wu%27s_line_algorithm), for example.
I'd expect that a line starting at x=1.98 should look almost like a line starting at x=2, rather than at x=1.

If you need simple truncation, cal `int()` or `round()` before calling `bresenham()`.
